name = "cloudwarden"
main = "src/index.ts"
compatibility_date = "2026-05-01"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "cloudwarden-db"
database_id = "eadc9ac1-4b24-45e1-b00b-cd32b3c081d7"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "ATTACHMENTS"
bucket_name = "cloudwarden-attachments"

[vars]
SIGNUPS_ALLOWED = "true"
SERVER_NAME = "CloudWarden"
